name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  job:
    strategy:
      fail-fast: false
      matrix:
        python_ver: # https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#python
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
        pip_ver: # https://pypi.org/project/pip/#history
          - '21.1.2'
          - '21.1.1'
          - '21.1'
          - '21.0.1'
          - '21.0'
          - '20.3.4'
          - '20.3.3'
          # '20.3.2' YANKED
          - '20.3.1'
          - '20.3'
          - '20.3b1'
          #   Supports 3.9
          #     https://pip.pypa.io/en/stable/news/#b1-2020-10-31
          #     https://github.com/pypa/pip/pull/8971
          - '20.2.4'
          - '20.2.3'
          - '20.2.2'
          - '20.2.1'
          - '20.2'
          - '20.2b1'
          - '20.1.1'
          - '20.1'
          - '20.1b1'
          - '20.0.2'
          - '20.0.1'
          # '20.0'   YANKED
          - '19.3.1'
          #   Supports 3.8
          #     https://pip.pypa.io/en/stable/news/#id298
          #     https://github.com/pypa/pip/pull/7219
          - '19.3'
          #   Later than 62dfd7d6fe11bfa0cd1d7376382c8e7b1275e38c
          #     Aug 26, 2019
          #     https://github.com/python/cpython/commit/62dfd7d6fe11bfa0cd1d7376382c8e7b1275e38c#diff-838d03b823aa8b092fbcc37dc43c35f14ba424a516e975f053a06dc9af45b507R102
          - '19.2.3'
          - '19.2.2'
          - '19.2.1'
          - '19.2'
          - '19.1.1'
          - '19.1'
          - '19.0.3'
          - '19.0.2'
          - '19.0.1'
          - '19.0'
          - '18.1'
          #   Supports 3.7
          #     https://pip.pypa.io/en/stable/news/#id490
          #     https://github.com/pypa/pip/pull/5561
    runs-on: windows-latest
    steps:
      - run: |
          python --version
          python -m pip --version
          pip -V

      - name: Python ${{ matrix.python_ver }}, pip ${{ matrix.pip_ver }}
        run: echo START!

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_ver }}

      - run: |
          python --version
          python -m pip --version
          pip -V
      - run: |
          pip install --user pip==${{ matrix.pip_ver }}
          python -m pip --version
          pip -V
      - run: |
          python --version
          python -m pip --version
          pip -V

      - name: VSCMD_ARG_TGT_ARCH does not exist
        run: |
          python -c "import distutils.util
          print(distutils.util.get_platform())"
      - name: VSCMD_ARG_TGT_ARCH is empty
        env:
          VSCMD_ARG_TGT_ARCH: ''
        run: |
          python -c "import distutils.util
          print(distutils.util.get_platform())"
      - name: VSCMD_ARG_TGT_ARCH is "x86"
        env:
          VSCMD_ARG_TGT_ARCH: 'x86'
        run: |
          python -c "import distutils.util
          print(distutils.util.get_platform())"
      - name: VSCMD_ARG_TGT_ARCH is "x64"
        env:
          VSCMD_ARG_TGT_ARCH: 'x64'
        run: |
          python -c "import distutils.util
          print(distutils.util.get_platform())"
      - name: VSCMD_ARG_TGT_ARCH is "arm"
        env:
          VSCMD_ARG_TGT_ARCH: 'arm'
        run: |
          python -c "import distutils.util
          print(distutils.util.get_platform())"
